import { Speciality } from './doctor';

export const specialities: Speciality[] = [
  {name: 'אונקולוגיה', category: 'base'},
  {name: 'אימונולוגיה קלינית ואלרגולוגיה', category: 'sub'},
  {name: 'אנדוקרינולוגיה', category: 'sub'},
  {name: 'אנדוקרינולוגית ילדים', category: 'sub'},
  {name: 'אנטומיה פתולוגית', category: 'base'},
  {name: 'ביוכימיה קלינית', category: 'base'},
  {name: 'בריאות הציבור', category: 'base'},
  {name: 'גנטיקה רפואית', category: 'sub'},
  {name: 'גסטרואנטרולוגיה', category: 'sub'},
  {name: 'גסטרואנטרולוגית ילדים', category: 'sub'},
  {name: 'גריאטריה', category: 'sub'},
  {name: 'גריאטריה', category: 'base'},
  {name: 'המטו-אונקולוגית ילדים', category: 'sub'},
  {name: 'המטולוגיה', category: 'sub'},
  {name: 'הרדמה', category: 'base'},
  {name: 'טיפול נמרץ ילדים', category: 'sub'},
  {name: 'טיפול נמרץ כללי', category: 'sub'},
  {name: 'יילוד וגינקולוגיה', category: 'base'},
  {name: 'כירורגיה אורולוגית', category: 'base'},
  {name: 'כירורגיה אורטופדית', category: 'base'},
  {name: 'כירורגיה ילדים', category: 'sub'},
  {name: 'כירורגיה ילדים', category: 'base'},
  {name: 'כירורגיה כללית', category: 'base'},
  {name: 'כירורגיה פלסטית', category: 'base'},
  {name: 'כירורגיה של בית החזה', category: 'base'},
  {name: 'כירורגית כלי דם', category: 'base'},
  {name: 'כירורגית של היד', category: 'sub'},
  {name: 'מחלות אף אוזן גרון וכירורגיית ראש וצוואר', category: 'base'},
  {name: 'מחלות זיהומיות', category: 'sub'},
  {name: 'מחלות עור ומין', category: 'base'},
  {name: 'מחלות עיניים', category: 'base'},
  {name: 'מחלות ריאה', category: 'sub'},
  {name: 'מחלות ריאה ילדים', category: 'sub'},
  {name: 'מיקרוביולוגיה קלינית', category: 'base'},
  {name: 'מנהל רפואי', category: 'sub'},
  {name: 'נאונטולוגיה', category: 'sub'},
  {name: 'נוירוכירורגיה', category: 'base'},
  {name: 'נוירולוגיה', category: 'base'},
  {name: 'נוירולוגית ילדים והתפתחות הילד', category: 'sub'},
  {name: 'נפרולוגיה', category: 'sub'},
  {name: 'נפרולוגית ילדים', category: 'sub'},
  {name: 'פסיכיאטריה', category: 'base'},
  {name: 'פסיכיאטריה של הילד והמתבגר', category: 'base'},
  {name: 'פרמקולוגיה קלינית', category: 'sub'},
  {name: 'קרדיולוגיה', category: 'sub'},
  {name: 'קרדיולוגית ילדים', category: 'sub'},
  {name: 'רדיולוגיה אבחנתית', category: 'base'},
  {name: 'ריאומטולוגיה', category: 'sub'},
  {name: 'רפואה גרעינית', category: 'base'},
  {name: 'רפואה דחופה', category: 'sub'},
  {name: 'רפואה דחופה', category: 'base'},
  {name: 'רפואה לשיכוך כאב', category: 'sub'},
  {name: 'רפואה משפטית', category: 'base'},
  {name: 'רפואה פיסיקלית ושיקום', category: 'sub'},
  {name: 'רפואה פיסיקלית ושיקום', category: 'base'},
  {name: 'רפואה פליאטיבית', category: 'sub'},
  {name: 'רפואה פנימית', category: 'base'},
  {name: 'רפואה תעסוקתית', category: 'base'},
  {name: 'רפואת המשפחה', category: 'base'},
  {name: 'רפואת ילדים', category: 'base'},
];
